### ISSUE TITLE
Legacy slack app migration

### ISSUE THREAD

**Issue by MrSmoke** [MrSmoke/TeaTime#95]
https://api.slack.com/authentication/migration

## Todo
- [x] Update scopes
  - `incoming-webhook`, `commands`
- [x] Replace `oauth.access` with `oauth.v2.access`
- [x] Replace `token` validation with [signed secrets](https://api.slack.com/authentication/verifying-requests-from-slack)
- [ ] Resubmit to app store
- [x] Update readme.md
